package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*UploadDropletCreated Droplet has been uploaded

swagger:response uploadDropletCreated
*/
type UploadDropletCreated struct {
}

// NewUploadDropletCreated creates UploadDropletCreated with default headers values
func NewUploadDropletCreated() *UploadDropletCreated {
	return &UploadDropletCreated{}
}

// WriteResponse to the client
func (o *UploadDropletCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

/*UploadDropletBadRequest Missing or invalid upload URI, or invalid timeout

swagger:response uploadDropletBadRequest
*/
type UploadDropletBadRequest struct {
}

// NewUploadDropletBadRequest creates UploadDropletBadRequest with default headers values
func NewUploadDropletBadRequest() *UploadDropletBadRequest {
	return &UploadDropletBadRequest{}
}

// WriteResponse to the client
func (o *UploadDropletBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*UploadDropletInternalServerError Droplet upload failed

swagger:response uploadDropletInternalServerError
*/
type UploadDropletInternalServerError struct {
}

// NewUploadDropletInternalServerError creates UploadDropletInternalServerError with default headers values
func NewUploadDropletInternalServerError() *UploadDropletInternalServerError {
	return &UploadDropletInternalServerError{}
}

// WriteResponse to the client
func (o *UploadDropletInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}

/*UploadDropletDefault Response code from upload request

swagger:response uploadDropletDefault
*/
type UploadDropletDefault struct {
	_statusCode int
}

// NewUploadDropletDefault creates UploadDropletDefault with default headers values
func NewUploadDropletDefault(code int) *UploadDropletDefault {
	if code <= 0 {
		code = 500
	}

	return &UploadDropletDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the upload droplet default response
func (o *UploadDropletDefault) WithStatusCode(code int) *UploadDropletDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the upload droplet default response
func (o *UploadDropletDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *UploadDropletDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
}
